org: luistorm23
app: serveles-mongodb
service: aws-node-http-api-project
frameworkVersion: '3'
useDotenv: true
# configValidationMode: error

params:
  default:
    dbName: test-serverless
  dev:
    connectionString: ${env:URL_DB}
    salt: ${env:SALT}
    jwtSecret: ${env:JWTSECRET}
  prod:

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    JWT_SECRET: ${param:jwtSecret}
    SALT: ${param:salt}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  
functions:
  sendResponse:
    handler: api/index.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./api/schemas/sendResponse.json)}
  getResult:
    handler: api/index.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get
  login:
    handler: api/index.login
    events:
      - httpApi:
          path: /api/login
          method: post
          request:
            schemas:
              application/json: ${file(./api/schemas/login.json)}
  createLogin:
    handler: api/index.createUser
    events:
      - httpApi:
          path: /api/createUser
          method: post
          request:
            schemas:
              application/json: ${file(./api/schemas/login.json)}
